### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by japanese-xevvo** [Termux-pod/termux-pod#12]
I have problem on my phone and on my emulator Win64 (Bluestacks).

i try `pip install future`
My phone:
` ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-oqplslun/future/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-oqplslun/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-oqplslun/future/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/data/data/com.termux/files/usr/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen failed: cannot locate symbol "ffi_closure_free" referenced by "/data/data/com.termux/files/usr/lib/python3.7/lib-dynload/_ctypes.cpython-37m.so"...
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

Emulator:
`pip install future==0.17.0
Collecting future==0.17.0
  Using cached https://files.pythonhosted.org/packages/85/aa/ba2e24dcb889d7e98733f87515d80b3512418b80ba79d82d2ddcd43fadf3/future-0.17.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/com.termux/files/usr/tmp/pip-install-1qhaw_bp/future/setup.py'"'"'; __file__='"'"'/data/data/com.termux/files/usr/tmp/pip-install-1qhaw_bp/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /data/data/com.termux/files/usr/tmp/pip-install-1qhaw_bp/future/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/data/data/com.termux/files/usr/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen failed: cannot locate symbol "ffi_closure_free" referenced by "/data/data/com.termux/files/usr/lib/python3.7/lib-dynload/_ctypes.cpython-37m.so"...
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

![image](https://user-images.githubusercontent.com/77848119/144866740-e06fd1c6-1a74-4d2c-832b-74abf750919c.png)
![image](https://user-images.githubusercontent.com/77848119/144866777-db831f9d-a0ee-430c-a62a-88f43989675b.png)

**Comment by japanese-xevvo** [comment]
But on Python 3.9.7 no problems

**Comment by kcubeterm** [comment]
Pip breaks due to libffi,  it means I should provide all related library as well. Better I should launch an apt repository that makes things easier.
